# refer from https://squidfunk.github.io/mkdocs-material/
site_name: 溯流
site_description: 笔记 
site_author: zexsphere
site_url: https://zexsphere.github.io/note

repo_name: 'zexsphere/note'
repo_url: https://github.com/zexsphere/note

copyright: Copyright &copy; 2023-2024 <a href="https://github.com/zexsphere" target="_blank" rel="noopener">zexsphere</a>



theme:
  name: material
  language: zh
  custom_dir: overrides
  # logo:  asserts/images/logo.png
  favicon: asserts/images/code-solid.svg
  palette:
    - scheme: custom
      # primary: orange
      accent: orange
      toggle:
        icon: material/lightbulb
        name: dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: eye-protection mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: light mode
  font:  
    text: 'LXGW WenKai Screen'
    code: 'Fira Code' 
  features:
    - navigation.instant     # 即时加载
    - navigation.tracking    # 锚点跟踪
    - navigation.indexes     # 次级索引页
    - navigation.tabs        # 导航选项卡
    - navigation.top         # 一键返回顶部
    - navigation.footer      # 上下页链接
    ### 代码
    - content.code.copy
    - content.code.annotate

extra_css:
  # - https://cdn.staticfile.org/lxgw-wenkai-webfont/1.6.0/style.css
  # - https://cdn.staticfile.org/lxgw-wenkai-screen-webfont/1.6.0/style.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.7.0/style.css
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zexsphere
    - icon: fontawesome/solid/envelope
      link: mailto:<zexscope@163.com>

plugins:

markdown_extensions:
  ### refer from https://shafish.cn/blog/mkdocs
  ### 术语
  - abbr            
  - pymdownx.snippets
  ### 提示
  - admonition           
  - pymdownx.details     
  - pymdownx.superfences 
  ### 按钮
  - attr_list
  ### 代码块
  - pymdownx.highlight:  
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  ### 内容标签栏
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  ### 表格
  - tables
  ### 格式化
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  ###图标
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  ### 图片
  - attr_list
  - md_in_html
  ### 列表
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

### 内容列表
nav:
  - 首页: 
    - index.md
    - changelog.md
  - 计算机科学: 
    - cs/index.md
    - 自动化工具: 
      - cs/tool/index.md
      - cs/tool/task.md
      - cs/tool/shell.md
      - cs/tool/tmux.md
      - cs/tool/vim.md
      - cs/tool/git.md
      - cs/tool/make.md
      - cs/tool/docker.md
      - cs/tool/toolbox.md
    - 编程语言: 
      - C++: cs/lang/cpp.md
    - 算法:
      - cs/algo/index.md
    - 课程学习: 
      - cs/course/index.md
    - 随笔:
      - cs/essay/index.md
      - cs/essay/0002.md
      - cs/essay/0004.md
      - cs/essay/0005.md
      - cs/essay/0006.md
      - cs/essay/0007.md
      - cs/essay/0008.md
      - cs/essay/0009.md
      - cs/essay/0010.md
      - cs/essay/0011.md
      - cs/essay/0012.md
      - cs/essay/0013.md
  - 软件使用:
    - sw/index.md 
    - sw/aseprite.md 
  - 阅读写作:
    - rw/index.md
    - rw/email.md
  - 游戏通关:
    - gm/katana-zero.md
    - gm/the-maze-detective.md
  - 健康:
    - health/index.md
    - health/vajra.md
    - 人纪:
      - 针灸:
        - health/human-age/acupuncture/index.md
  - 其他:
    - leetcode:
      - others/leetcode/index.md
    - others/8-legged.md
